OpenDominion/OpenDominion

- app/resources/assets/js/app.js
- app/resources/assets/js/ticker.js
- app/resources/views/layouts/master.blade.php
- app/resources/views/partials/tickers.blade.php
This change should provide tickers for your local time, the server time (UTC), and the time remaining before the next game tick (time until the next hour). The tickers will "tick" every second with the updated times.
Note that you'll need to rebuild your web assets (@WaveHack, I'm sure you already know :P).
Large displays:
Small displays (mobile):
Resolves #67
> Added local/server time and next tick tickers

- app/resources/views/pages/dominion/bank.blade.php
- app/resources/views/pages/dominion/construction.blade.php
- app/resources/views/pages/dominion/council/index.blade.php
- app/resources/views/pages/dominion/explore.blade.php
- app/resources/views/pages/dominion/military.blade.php
- app/resources/views/pages/dominion/realm.blade.php
- app/resources/views/pages/dominion/rezone.blade.php
- app/resources/views/pages/dominion/status.blade.php
This PR adds proper plural handling for strings in pages. It's using `str_plural` as suggested on #91. I believe I did that for all of them. Let me know if something is missing.
> Pluralizing strings in info boxes. Fix WaveHack/OpenDominion#91

- app/resources/views/pages/dominion/construction.blade.php
- app/resources/views/pages/dominion/military.blade.php
This PR replaces the help text below an item name by a tooltip in Building (construction) and Military lists. I'm using [Bootstrap's tooltip](https://getbootstrap.com/docs/3.3/javascript/#tooltips) instead of title attribute for the sake of a better touch/mobile experience.
> Replaced help text in lists by a tooltip. Using Bootstrap's tooltip.

- app/database/factories/ModelFactory.php
- app/database/migrations/2017_10_14_181002_drop_networth_column_from_dominions_table.php
- app/resources/views/pages/dominion/realm.blade.php
- src/Console/Commands/Game/TickCommand.php
- src/Factories/DominionFactory.php
- tests/Unit/Factories/DominionFactoryTest.php
This PR drops `networth` column from `dominions` table. It also removes the references to that column from the app (model, tests, views, etc.).
> Dropped networth column from dominion table. Fix WaveHack/OpenDominion/#96

- app/resources/views/pages/dominion/construction.blade.php
- app/resources/views/partials/dominion/advisor-selector.blade.php
- app/resources/views/partials/main-sidebar.blade.php
- app/routes/web.php
- src/Http/Controllers/Dominion/ConstructionController.php
This PR closes #92. It simply refactors some route names to replace `construction` by `construct`.
> Renamed 'construction' routes to 'construct'. Fix WaveHack/OpenDominion/#92

- app/resources/assets/sass/app.scss
- app/resources/views/pages/dominion/construction.blade.php
This PR closes WaveHack/OpenDominion/#98. It moves the barren land amount to the right and also gives more emphasis to the land type title, wrapping it in a `<h4>`.
> Improved readability of barren land indicator on construction page.

- src/Http/Controllers/Dominion/CouncilController.php
This PR closes #141. The threads are now sorted by the last activity. It considers the last post date or the thread creation date when it doesn't have any posts (A.K.A. a new thread).
> Changed council threads sorting to use the last activity to order.

- app/resources/views/pages/dominion/improvements.blade.php
- src/Http/Controllers/Dominion/ImprovementController.php
While adding improvements, the request parameter gets passed to the post request so the dropdown can be pre-selected with the previously selected resource.
> Select the previously chosen resource in the improvements dropdown

- src/Console/Commands/Game/TickCommand.php
#170 
So this fixed the ranking by looping over the daily rankings table for each round while checking the id and only setting the ranking if the round_ids are equal. 
It works but I guess I could see it taking a bit of time if we ever have a huge number of rounds?
> Daily Ranking Bug

- app/resources/views/errors/503.blade.php
- app/resources/views/partials/main-footer.blade.php
- app/routes/api.php
- src/Console/Commands/Game/TickCommand.php
- src/Models/Dominion.php
- src/Models/Round.php
- src/Services/Dominion/Actions/SpellActionService.php
- src/Services/Dominion/ProtectionService.php
- Fixes #188 
- Removes unused 'use' statements in files where no other instances of Carbon are being used.
> Replaces usages of Carbon\Carbon::now() with Laravel's built-in now() helper.

- src/Models/Race.php
Limit for relation is used for all objects relationships. So this was not visible before there where more than one race in a realm. The reason it's not in the rankings is because rankings queries db for every dominion. It is not done in a single query.
> Realm page networth calculation is off

- src/Services/Dominion/Actions/EspionageActionService.php
Changed base rate to 0.1%, and changed to floor instead of ceil. So you'll need atleast 1000 spi es before you start loosing them.
Solves #445
> Changed base rate to 0.1%, and changed to floor instead of ceil.

- src/Calculators/Dominion/SpellCalculator.php
Since the attacking dominions spells are checked first, they get cached. So if attacker has Ares on it doesn't matter if the defender has it. It will still be found in the cache.
> Active spells cache was leaking for invasions, solves dp bug.

- app/resources/views/pages/dominion/op-center/show.blade.php
Minor adjustments to ops center view templates.
- Addresses #466 adding tilde before units returning totals
- Adds colons after military unit names in clear sight (to be consistent with other rows and status page)
> ops center formatting

- app/database/migrations/2019_05_17_191915_create_unit_perks_table.php
- src/Calculators/Dominion/CasualtiesCalculator.php
- src/Calculators/Dominion/MilitaryCalculator.php
- src/Console/Commands/Game/DataSyncCommand.php
- src/Helpers/UnitHelper.php
- src/Models/Dominion.php
- src/Models/Race.php
- src/Models/RacePerkType.php
- src/Models/Unit.php
- src/Models/UnitPerk.php
- src/Models/UnitPerkType.php
- src/Services/Dominion/Actions/InvadeActionService.php
- src/Services/Dominion/SelectorService.php
This is required for some of the new races. It addresses the refactor mentioned in #277.
- Database migration for unit_perks pivot table
- belongsToMany relationships for race and unit perks
- Use Eloquent's sync method for game:data:sync
- Replaces unit->perkType with unit->getPerkValue(string)
> added support for multiple unit perks

- app/resources/views/pages/dominion/construction.blade.php
- src/Calculators/Dominion/Actions/ConstructionCalculator.php
- src/Services/Dominion/Actions/ConstructActionService.php
Fixes #442
ConstructionCalculator will now do the discounted land calc as coded in the ConstructActionService.
Also added a note on the construction page template, but not sure about what wording to use:
"Additionally, X acres from invasion can be built at reduced cost."
> fix issue where getMaxAfford didn't check discounted_land

- app/database/migrations/2019_06_02_193607_add_target_realm_id_to_info_ops_table.php
- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/op-center/show.blade.php
- app/resources/views/pages/dominion/town-crier.blade.php
- app/routes/web.php
- src/Helpers/SpellHelper.php
- src/Http/Controllers/Dominion/OpCenterController.php
- src/Http/Controllers/Dominion/TownCrierController.php
- src/Models/InfoOp.php
- src/Services/Dominion/Actions/SpellActionService.php
- src/Services/Dominion/InfoOpService.php
- Separated the clairvoyance ops from the rest in the op center table view / counts.
- Added a link to view/cast clairvoyance from individual dominion op center page (do we like this?)
- Hides links to results when both dominions are out-of-realm.
> Additional work on Clairvoyance

- app/data/races/darkelf.yml
- app/data/races/gnome.yml
- app/database/migrations/2019_05_17_191915_create_unit_perks_table.php
- app/resources/views/pages/dominion/invade.blade.php
- app/routes/api.php
- src/Calculators/Dominion/Actions/RezoningCalculator.php
- src/Calculators/Dominion/MilitaryCalculator.php
- src/Helpers/RaceHelper.php
- src/Http/Controllers/DebugController.php
- src/Http/Controllers/Dominion/APIController.php
- src/Http/Kernel.php
- src/Http/Requests/Dominion/API/InvadeCalculationRequest.php
- src/Providers/RouteServiceProvider.php
- src/Services/Dominion/API/InvadeCalculationService.php
- tests/Feature/TickTest.php
Features
- Adds new API route group with invasion calculator endpoint.
- Connected to existing frontend code with minimal changes.
- Updates unit OP/DP onload and when selecting a target.
- Takes into account building/land-based perks as well as target range/race perks.
Bugfixes
- Errors with default value of opposingForceRaceName
- Errors with RezoningCalculator constructor  
- Errors with multi-argument functions in DebugController
- Update validation for InvadeActionServiceRequest
- reverse order of offense_staggered_land_range (Dark Elf/Gnome)
- correct indentation on need_boats (Dark Elf)
- correct typo in perk (Dark Elf)
Todo
- Should be refactored a bit in the future to do most/all of the calculations on the backend.
> Update invasion calculator

- src/Calculators/Dominion/MilitaryCalculator.php
This caused an issue where the frontend would allow you to attack, but backend would incorrectly fail the 5:4 check. Invasion page should eventually pull all of these calculations from the API.
> Fix defense calculation for attacking forces

- src/Services/Dominion/Actions/InvadeActionService.php
Fixes #566 and also takes advantage of casualties being calculated before afterInvasionPerks to take casualties into account for plunder.
> Reorder handleCasualties and handleLandGrabs

- src/Services/Dominion/Actions/SpellActionService.php
Used dominion casting the spells incoming boats, and not the targets incoming boats.
> CS does not include incoming boats

- src/Calculators/NetworthCalculator.php
So, will give max power for land ratio based perks. It will be based on the actual land % for that type of perk. It will not give any extra for vs_race.
> Added use of getUnitPowerWithPerk from military calc in nw calc.

- src/Calculators/Dominion/CasualtiesCalculator.php
- src/Services/Dominion/TickService.php
- tests/Unit/Calculators/Dominion/CasualtiesCalculatorTest.php
Addresses another race condition (reverse of the one we fixed already) where performing actions during the tick can have unexpected results.
Starvation needed a minor refactor in addition to the simple changes to how we set the new resource values.
> use increment/decrement in tick

- app/config/markdown.php
Changed markdown config to render soft breaks as browser recognizable <br/> tag instead of a newline.
> Adjust line format in Council

- app/resources/views/pages/dominion/event/invasion.blade.php
- src/Helpers/BuildingHelper.php
- src/Services/Dominion/Actions/InvadeActionService.php
- Implemented both perks with a base percentage of 5% which scales based on the percentage of your attacking / defending force that has the perk. If you only have 25% leviathans and 75% sirens, you will only sink 1.25% of the attacker's boats. Leviathans only sink boats that were sent out on the attack.
- Implemented dock bonus that protects boats when being attacked (by Kraken).
> Merfolk sink boats perks

- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/town-crier.blade.php
- app/routes/web.php
- src/Http/Controllers/Dominion/OpCenterController.php
- src/Listeners/InfoOpCreating.php
- src/Services/Dominion/Actions/SpellActionService.php
- src/Services/GameEventService.php
This needed a little tweaking after allowing multiple ops of the same type.
- Don't display the same realm multiple times
- Fix data table for CV
- Reorder routes (caused 404 on my machine)
- Use realm number instead of ID in URL
This does not currently allow viewing older CVs (needs an info_op id or something in the URL to identify which one you're looking at). Think this is fine for next round?
> Adjustments for clairvoyance

- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/op-center/show.blade.php
- src/Services/Dominion/InfoOpService.php
getNetworth, getLand, and getNumberOfActiveInfoOps will now use the collection of infoOps already queried at the controller level instead of looking them up separately.
> Fix very slow load time for Op Center index

- src/Services/RealmFinderService.php
Should continue loop instead if I am not mistaken. Otherwise it should result in false negative to filter?
Solves problem with potential false negatives in filter that selects random realm.
Please advise on how I should be testing this. I can set up and test when I get home. @stromblom could probably check or help me get started.
> Replace return false to filter when pack is closed with continue.

- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
Surreal perception was mistakenly being applied to info ops as well as theft. The scribes specifically state "non-information gathering" ops. https://dominion.opendominion.net/scribes/ops.html
> Surreal perception shouldn't affect info ops

- src/Http/Controllers/SettingsController.php
This is an issue as old as time. HTML forms do not send a value for unchecked checkboxes. Fix will iterate through possible values and set them to false if they were not submitted in the form data.
#670
> Fix notifications always set to true

- src/Console/Commands/Game/RoundOpenCommand.php
Renamed realmSize to realm-size (dash-case) as well as pack-size
Renamed realmSize to realm-size (dash-case) as well as pack-size in RoundOpenCommand.php
[https://github.com/WaveHack/OpenDominion/issues/470](https://github.com/WaveHack/OpenDominion/issues/470)
php artisan command runs properly, no errors.
- [x ] I have read the **CONTRIBUTING** document.
> Dash case fix

- README.md
This updates status bars in README.md, which are broken due to progressed.io no longer being active. I've replaced these with similar status bars from [progress-bar.dev](https://progress-bar.dev/), which is inspired by progressed.io
This change is required to keep the README progress up to date. I don't believe there's an open issue for this to be linked here.
I've tested this by previewing README.md locally and verifying that progress bars appear with the appropriate values
> Update broken status bars

- app/resources/css/skin-classic.css
- src/Services/Dominion/QueueService.php
- src/Services/Dominion/TickService.php
Population and peasant growth was found to be buggy in ODA.
- Precalculate population changes before looking at incoming military for next hour.
- Remove queueCache, this was no longer needed after adding the dominion->queues relation. The queue data gets attached to the selected dominion object. There were several bugs here where units sent out on attack were not being included in the population calculator methods.
> Fix population bugs

- app/resources/css/skin-classic.css
- src/Calculators/Dominion/MilitaryCalculator.php
- src/Calculators/Dominion/PopulationCalculator.php
- src/Services/Dominion/Actions/ConstructActionService.php
- src/Services/Dominion/Actions/ExploreActionService.php
- src/Services/Dominion/Actions/Military/TrainActionService.php
- src/Services/Dominion/QueueService.php
- src/Services/Dominion/TickService.php
This fix removes some hacky stuff I did in the tickservice and replaces it with a flag on the QueueService class that will ignore queues for the following hour (hours=1) when doing the precalculateTick call in TickService. Otherwise, buildings and incoming troops will be counted twice when determining max population and weird things will happen.
There's also a minor change to queue resources prior to saving a dominion in the action services, which also interferes with the tick calculation. This one made you wait an additional hour before your incomings were counted (therefore offsetting the other bug and making them nearly unnoticeable in most cases).
> Fix additional population bugs

- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/realm.blade.php
- app/resources/views/pages/dominion/search.blade.php
- app/resources/views/pages/dominion/town-crier.blade.php
- src/Http/Controllers/Dominion/SearchController.php
- src/Http/Controllers/Dominion/TownCrierController.php
- src/Services/GameEventService.php
A few improvements related to search and crier as discussed on discord.
- link the realm numbers in crier to realm pages (reverted)
- add a link from realm page to crier for that realm only
- limit global crier to 3 days because it's going to get really long (single realm still 7)
- fix default ordering of op center (bug)
- show own realm in search
- default to showing all results in search
> QoL Improvements

- app/resources/views/pages/dominion/search.blade.php
- src/Services/Dominion/TickService.php
- Fix an issue with the search page Limit values being flipped.
- Update daily bonuses in a single query and prevent a partial update in the event of an error.
> Small Fixes

- src/Services/Dominion/Actions/InvadeActionService.php
This was incorrectly returning the fastest units instead of slowest.
> fix bug with slowestUnitReturnHours

- .github/workflows/tests.yml
Set the PHP version in the Github Action pipeline to PHP 7.3
Set the PHP version in the Github Action pipeline to PHP 7.3
Because Laravel 5.7 apparently doesn't work with PHP 7.4 (https://github.com/laravel/framework/issues/30737), which is currently supplied by default in the Ubuntu 16.04 container. Even though the docs (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1604-lts) of Github Actions, don't mention anything about PHP 7.4.
Screenshot of default PHP version being PHP 7.4
Not applicable.
> Fixed GitHub actions

- src/Models/Dominion.php
- src/Services/Dominion/Actions/ConstructActionService.php
- src/Services/Dominion/Actions/ExploreActionService.php
- src/Services/Dominion/Actions/ImproveActionService.php
- src/Services/Dominion/Actions/Military/TrainActionService.php
- src/Services/Dominion/Actions/ReleaseActionService.php
- src/Services/Dominion/QueueService.php
- Overriding Dominion::getDirty changes the update query to increment/decrement the current values instead of just setting it to something that was calculated beforehand
- Manually updated dominion_queues query to increment queued resource amount
- Removes nested transaction present in queueResources that prevented updating queues even after other resources were spent
- Allows precalculateTick call on save even when no attributes were changed (accounting for changes to active_spells table)
> Proper fix for Race Conditions

- app/database/migrations/2020_05_05_020705_add_locked_at_to_dominions_table.php
- app/resources/views/layouts/topnav.blade.php
- app/resources/views/pages/dominion/realm.blade.php
- app/resources/views/pages/dominion/search.blade.php
- app/resources/views/pages/round/register.blade.php
- app/resources/views/pages/user-agreement.blade.php
- app/resources/views/partials/alerts.blade.php
- app/resources/views/partials/user-agreement.blade.php
- app/routes/web.php
- src/Calculators/Dominion/RangeCalculator.php
- src/Http/Controllers/Dominion/CouncilController.php
- src/Http/Controllers/Dominion/OpCenterController.php
- src/Http/Controllers/HomeController.php
- src/Models/Dominion.php
- src/Models/Round.php
- src/Services/Dominion/Actions/DailyBonusesActionService.php
- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/Actions/GovernmentActionService.php
- src/Services/Dominion/Actions/GuardMembershipActionService.php
- src/Services/Dominion/Actions/InvadeActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
- src/Services/Dominion/HistoryService.php
- src/Services/Dominion/TickService.php
- src/Traits/DominionGuardsTrait.php
An administrator can lock a dominion by setting the locked_at attribute. This will prevent any actions performed by or against the dominion via DominionGuardsTrait, suspends hourly ticks, prevents viewing Council, and shows a 'Locked' badge beside the dominion name on the Realm/Search pages.
A subsequent commit will add a user agreement to the round registration form.
> Updated PR for administrative suspension
