OpenDominion/OpenDominion

- app/resources/assets/js/bank.js
- app/resources/assets/sass/app.scss
- app/resources/views/pages/dominion/national-bank.blade.php
- app/resources/views/partials/main-sidebar.blade.php
- app/routes/web.php
- src/Calculators/Dominion/Actions/BankingCalculator.php
- src/Contracts/Calculators/Dominion/Actions/BankingCalculator.php
- src/Contracts/Services/Dominion/Actions/BankActionService.php
- src/Http/Controllers/Dominion/BankController.php
- src/Http/Requests/Dominion/Actions/BankActionRequest.php
- src/Providers/AppServiceProvider.php
- src/Services/Dominion/Actions/BankActionService.php
> Add National Bank.

- src/Console/Commands/RoundStartCommand.php
> Open flag added to round:start command

- app/resources/views/pages/dominion/rezone.blade.php
> Rename Available header to Barren for consistency

- src/Http/Controllers/Dominion/BankController.php
- src/Http/Controllers/Dominion/ConstructionController.php
- src/Http/Controllers/Dominion/ExplorationController.php
- src/Http/Controllers/Dominion/MilitaryController.php
- src/Http/Controllers/Dominion/RezoneController.php
- src/Services/Dominion/Actions/BankActionService.php
- src/Services/Dominion/Actions/ConstructActionService.php
- src/Services/Dominion/Actions/DestroyActionService.php
- src/Services/Dominion/Actions/ExploreActionService.php
- src/Services/Dominion/Actions/Military/ChangeDraftRateActionService.php
- src/Services/Dominion/Actions/Military/TrainActionService.php
- src/Services/Dominion/Actions/ReleaseActionService.php
- src/Services/Dominion/Actions/RezoneActionService.php
PR for https://github.com/WaveHack/OpenDominion/issues/90
> Add a structured array return value to all action services

- src/Services/Dominion/Actions/ReleaseActionService.php
This refactors the calculation of the release action string.
> Refactor the release action string

- app/database/migrations/2017_10_15_112057_change_dominions_wizard_spy_strength_type.php
Issue: #137 
Happy hacktoberfest ;)
> Dominions wizard and spy strength changed from int to float.

- app/database/migrations/2017_10_15_223241_add_daily_bonuses_columns.php
- app/resources/views/pages/dominion/bonuses.blade.php
- app/resources/views/partials/main-sidebar.blade.php
- app/routes/web.php
- src/Console/Commands/Game/TickCommand.php
- src/Http/Controllers/Dominion/DailyBonusesController.php
- src/Http/Requests/Dominion/Actions/DailyBonusesLandActionRequest.php
- src/Http/Requests/Dominion/Actions/DailyBonusesPlatinumActionRequest.php
- src/Providers/AppServiceProvider.php
- src/Services/Dominion/Actions/DailyBonusesActionService.php
PR for https://github.com/WaveHack/OpenDominion/issues/54
> Add daily bonuses

- src/Http/Controllers/Dominion/ConstructionController.php
> Fix being unable to destroy buildings

- CONTRIBUTING.md
Issue   #159.
For contributors receiving "Application Encryption error" on clone and startup of dev server.
> Issue 159: Add artisan key generate fix to contributing.md

- composer.json
- src/Services/Dominion/Actions/Military/TrainActionService.php
- src/helpers.php
Fix unit training return message #156
> #156 Update TrainActionService.php

- app/resources/views/partials/main-footer.blade.php
#171 Went ahead and added a day to the counter
> Added One Day To The Counter

- app/resources/views/pages/auth/email.blade.php
- app/resources/views/pages/auth/login.blade.php
- app/resources/views/pages/auth/reset.blade.php
- app/routes/web.php
- app/storage/app/.gitignore
- src/Http/Controllers/Auth/ForgotPasswordController.php
- src/Http/Controllers/Auth/ResetPasswordController.php
Hi I finally got around to implementing this. I based it off the functionality already built into Laravel. Please let me know what you think.
> Reset password

- app/resources/views/pages/dashboard.blade.php
- app/resources/views/pages/dominion/bank.blade.php
- app/resources/views/pages/dominion/bonuses.blade.php
- app/resources/views/pages/dominion/construction.blade.php
- app/resources/views/pages/dominion/council/create.blade.php
- app/resources/views/pages/dominion/council/thread.blade.php
- app/resources/views/pages/dominion/destroy.blade.php
- app/resources/views/pages/dominion/explore.blade.php
- app/resources/views/pages/dominion/improvements.blade.php
- app/resources/views/pages/dominion/magic.blade.php
- app/resources/views/pages/dominion/military.blade.php
- app/resources/views/pages/dominion/realm.blade.php
- app/resources/views/pages/dominion/release.blade.php
- app/resources/views/pages/dominion/rezone.blade.php
- app/resources/views/pages/round/register.blade.php
- app/resources/views/partials/auth-user-nav.blade.php
> Refactor {!! csrf_field() !!} to {{ csrf_field() }}

- app/resources/views/pages/auth/login.blade.php
- app/resources/views/pages/auth/passwords/email.blade.php
- app/resources/views/pages/auth/passwords/reset.blade.php
- app/resources/views/pages/auth/register.blade.php
- app/resources/views/pages/dashboard.blade.php
- app/resources/views/pages/dominion/bank.blade.php
- app/resources/views/pages/dominion/bonuses.blade.php
- app/resources/views/pages/dominion/construction.blade.php
- app/resources/views/pages/dominion/council/create.blade.php
- app/resources/views/pages/dominion/council/thread.blade.php
- app/resources/views/pages/dominion/destroy.blade.php
- app/resources/views/pages/dominion/explore.blade.php
- app/resources/views/pages/dominion/improvements.blade.php
- app/resources/views/pages/dominion/magic.blade.php
- app/resources/views/pages/dominion/military.blade.php
- app/resources/views/pages/dominion/realm.blade.php
- app/resources/views/pages/dominion/release.blade.php
- app/resources/views/pages/dominion/rezone.blade.php
- app/resources/views/pages/round/register.blade.php
- app/resources/views/partials/auth-user-nav.blade.php
> Use the new csrf helper in laravel 5.6

- CONTRIBUTING.md
I was reading you're CONTRIBUTING.md as I am interested in contributing to this awesome looking project. I came across some language error so I fixed it as per my understanding of the English language.
> Change some content in CONTRIBUTING.md

- app/resources/views/pages/dominion/council/index.blade.php
- app/resources/views/pages/dominion/council/thread.blade.php
- app/resources/views/pages/dominion/status.blade.php
- src/Services/Dominion/Actions/SpellActionService.php
> Changed to use ruler name instead of users display name.

- app/resources/views/pages/dominion/status.blade.php
> Switched information and under-protection boxes on status page

- app/data/races/dwarf.yml
- app/data/races/goblin.yml
- src/Calculators/Dominion/PopulationCalculator.php
> Added new perk for barren land pop bonus.

- src/Events/UserLoggedOutEvent.php
- src/Http/Controllers/Auth/LoginController.php
- src/Listeners/Subscribers/ActivitySubscriber.php
- src/Listeners/Subscribers/AnalyticsSubscriber.php
> WIP: Add event for user logging out

- package-lock.json
- src/Services/Dominion/Actions/EspionageActionService.php
- tests/Unit/Services/Action/EspionageActionServiceTest.php
> Added new formula for spy losses.

- app/resources/views/pages/dominion/realm.blade.php
Have **NOT** tested this. Opened for your review @WaveHack
> Removed ruler name, added user name for packies.

- CHANGELOG.md
- app/resources/views/pages/dominion/rankings.blade.php
- src/Services/Dominion/TickService.php
> Moved rank update to hour tick, added check for modulo 6 on hour.

- src/Calculators/Dominion/MilitaryCalculator.php
> Wrong resource key was used.

- src/Http/Controllers/Dominion/RealmController.php
> Added new sorting, which can handle numbers above 1k land.

- src/Calculators/NetworthCalculator.php
> Moved to using MilitaryCalc in NW calc

- src/Calculators/Dominion/PopulationCalculator.php
> Added returning units to pop count.

- app/resources/views/pages/dominion/military.blade.php
- src/Http/Controllers/Dominion/MilitaryController.php
> Added military calc to military view, for first 4 slots.

- app/resources/views/pages/dominion/status.blade.php
- src/Http/Controllers/Dominion/StatusController.php
- src/Services/Dominion/Actions/SpellActionService.php
> Added boats from queue to status page and clear sight

- app/resources/views/pages/dominion/town-crier.blade.php
- src/Http/Controllers/Dominion/TownCrierController.php
> TC includes own invades

- app/resources/views/pages/auth/login.blade.php
> Make "remember me" checked by default

- app/data/races/darkelf.yml
- app/resources/views/pages/dominion/advisors/statistics.blade.php
- app/resources/views/pages/dominion/invade.blade.php
- app/resources/views/pages/dominion/military.blade.php
- src/Calculators/Dominion/CasualtiesCalculator.php
- src/Calculators/Dominion/MilitaryCalculator.php
- src/Helpers/RaceHelper.php
- src/Helpers/SpellHelper.php
- src/Helpers/UnitHelper.php
- src/Services/Dominion/Actions/InvadeActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
I piggy-backed off of some of the Gnome stuff, but it doesn't look to be quite finished.
Everything is implemented, but this is still slightly WIP because the calculations on the invasion page should take the target size into account (gnome too). I'll discuss further on Discord.
> Dark Elves

- src/Calculators/Dominion/RangeCalculator.php
> Changed default range, lower will be EG upper will stay as RG. 

- app/resources/views/pages/dominion/espionage.blade.php
- app/resources/views/pages/dominion/magic.blade.php
- src/Http/Controllers/Dominion/EspionageController.php
- src/Http/Controllers/Dominion/MagicController.php
Fixes #426 using a session flash value on redirect.
> keep selected target dominion after failed operation

- app/resources/views/pages/dominion/op-center/index.blade.php
> Removed range limit in ops center. 

- src/Calculators/Dominion/MilitaryCalculator.php
- src/Calculators/Dominion/PopulationCalculator.php
- src/Calculators/Dominion/PrestigeCalculator.php
- src/Calculators/Dominion/ProductionCalculator.php
The things in InvadeActionService that handle prestige, should be moved into this class. But I'll leave that for another time.
> Refactored prestige handling

- app/resources/views/pages/dominion/advisors/rankings.blade.php
- app/resources/views/pages/dominion/council/index.blade.php
- app/resources/views/pages/dominion/council/thread.blade.php
- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/op-center/show.blade.php
- app/resources/views/pages/dominion/status.blade.php
- app/resources/views/pages/dominion/town-crier.blade.php
- app/resources/views/pages/home.blade.php
- app/resources/views/pages/staff/administrator/dominions/index.blade.php
- app/resources/views/pages/staff/administrator/users/index.blade.php
- app/resources/views/partials/notification-nav.blade.php
As discussed, the diff format is not really helpful. And the hover does not work on phones.
> Removed the usage of diffForHumans

- app/resources/views/pages/round/register.blade.php
- src/Helpers/RaceHelper.php
This one will require a manual merge with the additional descriptions I added in #521 
- Moved race perk descriptions into separate helper function
- Perk display HTML is automatically generated from db
- Updated registration page UI
> update race selection frontend

- src/Helpers/UnitHelper.php
Fixes #533
This stuff is really messy, but it works. Additional cleanup should be done with #502
> Additional unit perk descriptions

- src/Calculators/Dominion/MilitaryCalculator.php
- tests/Unit/Calculators/Dominion/MilitaryCalculatorTest.php
Added tests for unit power perks.
Fixed a bug where a fourth parameter was expected for defense_from_land (typo in commit message)
> Tests / bugfix for unit power perks

- src/Calculators/Dominion/Actions/TrainingCalculator.php
- src/Models/Race.php
> Added the actual code for arch mage cost perk.

- app/data/races/firewalker.yml
- src/Calculators/Dominion/CasualtiesCalculator.php
- src/Helpers/UnitHelper.php
- src/Services/Dominion/Actions/InvadeActionService.php
Fixed and refatored to look like the code for op/dp_vs_race perk
> Bugfix immortal_vs

- src/Services/Dominion/Actions/BankActionService.php
- src/Services/Dominion/Actions/ConstructActionService.php
- src/Services/Dominion/Actions/DailyBonusesActionService.php
- src/Services/Dominion/Actions/DestroyActionService.php
- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/Actions/ExploreActionService.php
- src/Services/Dominion/Actions/ImproveActionService.php
- src/Services/Dominion/Actions/InvadeActionService.php
- src/Services/Dominion/Actions/Military/TrainActionService.php
- src/Services/Dominion/Actions/ReleaseActionService.php
- src/Services/Dominion/Actions/RezoneActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
Uses the Laravel query builder's increment and decrement methods instead of setting a pre-calculated total in Action Services. This could also be done within the TickService, but needs some testing to see what difference it makes in performance.
> Fix race condition around hour change

- src/Services/Dominion/Actions/SpellActionService.php
My Wizard Guild spell cost reduction only changed the frontend, not the actual cost. Needed to fix the action service which was calculating the spell cost separately.
> Fix spell action service mana cost

- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
Ratio | Old | New
-- | -- | --
2 | 0.754 | 0.956
1.95 | 0.7458286 | 0.942779
1.9 | 0.7372558 | 0.929156
1.85 | 0.7282687 | 0.915119
1.8 | 0.7188544 | 0.900654
1.75 | 0.709 | 0.88575
1.7 | 0.6986926 | 0.870393
1.65 | 0.6879193 | 0.854569
1.6 | 0.6766672 | 0.838267
1.55 | 0.6649234 | 0.821473
1.5 | 0.652675 | 0.804175
1.45 | 0.6399091 | 0.786359
1.4 | 0.6266128 | 0.768013
1.35 | 0.6127732 | 0.749123
1.3 | 0.5983774 | 0.729677
1.25 | 0.5834125 | 0.709663
1.2 | 0.5678656 | 0.689066
1.15 | 0.5517238 | 0.667874
1.1 | 0.5349742 | 0.646074
1.05 | 0.5176039 | 0.623654
1 | 0.4996 | 0.6006
0.95 | 0.4809496 | 0.5769
0.9 | 0.4616398 | 0.55254
0.85 | 0.4416577 | 0.527508
0.8 | 0.4209904 | 0.50179
0.75 | 0.399625 | 0.475375
0.7 | 0.3775486 | 0.448249
0.65 | 0.3547483 | 0.420398
0.6 | 0.3312112 | …
> Tweaked values in spy/wiz success formulae.

- app/resources/views/partials/dominion/op-center/box.blade.php
by popular demand!
from my WIP branch
> fix op center scroll on mobile

- app/resources/views/pages/valhalla/round.blade.php
- src/Http/Controllers/ValhallaController.php
Fixes #545
Races with a space in the name (Dark Elf, Wood Elf) and those unable to be converted to singular presented a problem.  I changed the URL to be singular and use additional hyphens for spaces.
> Add new races to valhalla

- app/resources/views/pages/dominion/status.blade.php
- src/Http/Controllers/Dominion/MiscController.php
- src/Http/Controllers/Dominion/StatusController.php
- Notification dropdown menu now marks as read instead of deleting.
- New paginated 'Recent News' section on Status page.
> Permanent notifications

- app/resources/views/pages/dominion/espionage.blade.php
- app/resources/views/pages/settings.blade.php
- src/Calculators/Dominion/SpellCalculator.php
- src/Helpers/EspionageHelper.php
- src/Helpers/NotificationHelper.php
- src/Helpers/SpellHelper.php
- src/Models/Dominion.php
- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/Actions/SpellActionService.php
- src/Services/NotificationService.php
Implements:
- Resource theft using all of the constraints from the wiki: https://opendominion.miraheze.org/wiki/Espionage#Resource_Theft
- Forest Haven stolen plat reduction
- Fool's Gold
- Spell cooldowns
- No theft first seven days
> Resource Theft

- src/Http/Controllers/ValhallaController.php
Valhalla was taking the first 100 dominions from the database and then ordering them, rather than the reverse :P
Fixes #518
> Fix valhalla cutoff

- src/Calculators/Dominion/CasualtiesCalculator.php
> Starvation formula changes

- src/Console/Commands/Game/RoundOpenCommand.php
- src/Services/RealmFinderService.php
I reworked this a bit. It now performs all of the pack checks (on non-empty realms) in a filter function and then orders eligible realms by the current number of dominions and chooses randomly from the 3 emptiest.
It will also create 20 empty realms when registration opens for a mixed alignment round (don't forget the --mixedAlignment flag).
It's still not perfect, but I think this will work for next round.
> Randomize realm selection

- app/resources/views/pages/home.blade.php
- app/resources/views/pages/scribes/race.blade.php
- src/Helpers/LandHelper.php
- src/Http/Controllers/ScribesController.php
> Added home land type and icons

- app/resources/views/pages/dominion/government.blade.php
> Adjust government layout on mobile

- app/resources/views/pages/dominion/espionage.blade.php
- app/resources/views/pages/dominion/government.blade.php
- src/Http/Controllers/Dominion/GovernmentController.php
- src/Services/Dominion/Actions/EspionageActionService.php
- src/Services/Dominion/GuardMembershipService.php
Fixes the issue reported by Dreki in dev-feedback. The template wasn't updated when isGuardMember was added.
> Fix issue with royal guard button

- src/Listeners/InfoOpCreating.php
> Fix bug with Clairvoyance

- src/Calculators/Dominion/CasualtiesCalculator.php
> Changed calculation to use units sent, not units home. #711

- app/resources/views/pages/scribes/index.blade.php
- src/Http/Controllers/ScribesController.php
Also includes the implemented information.
> #730 Buildings added to scribes

- app/resources/views/pages/home.blade.php
- src/Http/Controllers/HomeController.php
> #734 Added top 10 land ranking from current round to front page

- app/resources/views/pages/dominion/op-center/index.blade.php
- app/resources/views/pages/dominion/town-crier.blade.php
- app/routes/web.php
- src/Helpers/SpellHelper.php
- src/Http/Controllers/Dominion/TownCrierController.php
- src/Services/Dominion/InfoOpService.php
- src/Services/GameEventService.php
Quickest implementation of global TC that I could manage.
> Global Town Crier

- app/resources/views/pages/scribes/magic.blade.php
- app/resources/views/pages/scribes/techs.blade.php
- app/resources/views/partials/scribes/nav.blade.php
- app/routes/web.php
- src/Helpers/TechHelper.php
- src/Http/Controllers/ScribesController.php
> Add techs to scribes

- app/resources/views/pages/home.blade.php
- src/Http/Controllers/RoundController.php
Fixes #548 and also adds a link to dashboard on the homepage when logged in.
> Automatically select dominion when registering

- app/resources/views/pages/valhalla/round.blade.php
> Extended round information on valhalla page.

- app/resources/views/pages/dominion/town-crier.blade.php
- src/Http/Controllers/Dominion/TownCrierController.php
> Add range tool tip and date dividers to tc

- app/resources/views/pages/dominion/advisors/status.blade.php
- app/resources/views/partials/dominion/advisor-selector.blade.php
- app/routes/web.php
- src/Http/Controllers/Dominion/AdvisorsController.php
> Added status advisor for packies

- app/resources/views/partials/dominion/info/land-incoming-table.blade.php
- app/resources/views/partials/dominion/info/land-table.blade.php
- src/Mappers/Dominion/InfoMapper.php
> Added totals to land advisor

- CHANGELOG.md
- src/Services/Dominion/Actions/DestroyActionService.php
Based it on master, but can be moved to develop.
> Fixed Urg Smash build cost refund to be based on raw cost.

- src/Services/Dominion/Actions/DestroyActionService.php
So, max recovered per acre should not be higher than current modded build cost per acre.
> Re-re-reworked the urg smash code.

- app/data/techs.yml
Properly capitalizes my name in techs.
Yes
No
N/A
> Properly capitalize my name, dang it
